### ISSUE TITLE
Installation instructions

### ISSUE THREAD

**Issue by logiclrd** [smokey5787/city-pixels-loading#1]
How does one install this? Could you add some more details to README.md perhaps? :-)

**Comment by smokey5787** [comment]
Hi to install download and exctract then copy to `/home/USERNAME/.local/share/plasma/look-and-feel`
Yes I've been meaning to get around to including this in the Readme's for quite some time now

**Comment by logiclrd** [comment]
Thanks :-)

**Comment by logiclrd** [comment]
Hey, I've made my own splash screen, an animated version of "city pixels", and I'd like to publish it. Your splash screen has a category of "Plasma Splashscreens". I haven't been able to find this category in the dynamically-loaded multi-level dropdowns shown by pling.com. How did you find that category? :-)

**Comment by logiclrd** [comment]
Oh, I think I found it. Pling seems to have gone down for the time being, but on a Reddit post I found this:

> Submit under 'Linux/Unix Desktops>Desktop Themes>KDE>KDE Plasma>Plasma Splashscreens'

**Comment by logiclrd** [comment]
If you're curious: https://store.kde.org/p/2167294

**Comment by smokey5787** [comment]
Very nice, sorry I didn't get back to you sooner to help. Yer it can be a bit confusing when posting on pling
